In [1]:
from geopy.geocoders import Nominatim
import pandas as pd
geolocator = Nominatim(user_agent="ukge-constituency-locations")

In [2]:
def get_lat_long(address):
    print(address)
    location = geolocator.geocode(address +", United Kingdom")
    if location is None:
        print("N")
        location = geolocator.geocode(address)
    if location is None:
        print("NN")
        location = geolocator.geocode(address.split(" ")[0] + ", United Kingdom")
    print(location.address)
    print(location.latitude, location.longitude)
    return location.latitude, location.longitude

In [3]:
# lat_dict = {}
# long_dict = {}
# for c in cons:
#     lat, long = get_lat_long(c)
#     lat_dict[c] = lat
#     long_dict[c] = long


# df["Latitude"] = df["New constituency name"].apply(lambda x: lat_dict[x])
# df["Longitude"] = df["New constituency name"].apply(lambda x: long_dict[x])
#Takes 8 min

In [4]:
df = pd.read_csv("outputs/resultsclusteredconstituencieslocations.csv")
# "UKGE/outputs/resultsclusteredconstituencieslocations.csv"

In [5]:
df["Latitude"].median()

52.340217100000004

In [6]:
df[df["Latitude"]>59]
df[df["Latitude"]<50]

Empty DataFrame
Columns: [Unnamed: 0, ONS code, New constituency name, Total population, Aged 15 years and under, Aged 16 to 24 years, Aged 25 to 34 years, Aged 35 to 49 years, Aged 50 to 64 years, Aged 65 years and over, Cluster, 2019_Results, 2017_Results, 2015_Results, 2010_Results, 2005_Results, Ref16_Results, Low_Confidence_Imputation, 2019_Resultscon, 2019_Resultslab, 2019_Resultslib, 2019_Resultsref, 2019_Resultsnat, 2019_Resultsoth, 2019_Resultstot, 2019_Resultscon_pc, 2019_Resultslab_pc, 2019_Resultslib_pc, 2019_Resultsref_pc, 2019_Resultsnat_pc, 2019_Resultsoth_pc, 2017_Resultscon, 2017_Resultslab, 2017_Resultslib, 2017_Resultsref, 2017_Resultsnat, 2017_Resultsoth, 2017_Resultstot, 2017_Resultscon_pc, 2017_Resultslab_pc, 2017_Resultslib_pc, 2017_Resultsref_pc, 2017_Resultsnat_pc, 2017_Resultsoth_pc, 2015_Resultscon, 2015_Resultslab, 2015_Resultslib, 2015_Resultsref, 2015_Resultsnat, 2015_Resultsoth, 2015_Resultstot, 2015_Resultscon_pc, 2015_Resultslab_pc, 2015_Resultslib_pc, 2015_Resultsref_pc, 2015_Resultsnat_pc, 2015_Resultsoth_pc, 2010_Resultscon, 2010_Resultslab, 2010_Resultslib, 2010_Resultsref, 2010_Resultsnat, 2010_Resultsoth, 2010_Resultstot, 2010_Resultscon_pc, 2010_Resultslab_pc, 2010_Resultslib_pc, 2010_Resultsref_pc, 2010_Resultsnat_pc, 2010_Resultsoth_pc, 2005_Resultscon, 2005_Resultslab, 2005_Resultslib, 2005_Resultsref, 2005_Resultsnat, 2005_Resultsoth, 2005_Resultstot, 2005_Resultscon_pc, 2005_Resultslab_pc, 2005_Resultslib_pc, 2005_Resultsref_pc, 2005_Resultsnat_pc, 2005_Resultsoth_pc, EngReg, Scot, Region, Cluster Des, Latitude, Longitude]
Index: []

[0 rows x 89 columns]

In [7]:
df[df["Longitude"]>5]
df[df["Longitude"]<-5]

,Unnamed: 0,ONS code,New constituency name,Total population,Aged 15 years and under,Aged 16 to 24 years,Aged 25 to 34 years,Aged 35 to 49 years,Aged 50 to 64 years,Aged 65 years and over,...,2005_Resultslib_pc,2005_Resultsref_pc,2005_Resultsnat_pc,2005_Resultsoth_pc,EngReg,Scot,Region,Cluster Des,Latitude,Longitude
4,4,W07000082,Alyn and Deeside,102072,0.181960,0.089956,0.130467,0.191326,0.208382,0.197909,...,0.174920,0,0.044298,0.044434,0,False,Wales,Brexit,57.274096,-5.515916
93,93,E14001148,Camborne and Redruth,99095,0.176689,0.092618,0.114617,0.179575,0.206943,0.229557,...,0.376771,0,0.000000,0.081955,South West,False,South West,Marginal,50.214674,-5.330508
475,475,E14001511,St Ives,88509,0.154116,0.077764,0.094090,0.162353,0.230898,0.280779,...,0.497245,0,0.000000,0.085032,South West,False,South West,Conservative,50.214906,-5.479508
520,520,E14001554,Truro and Falmouth,94888,0.153033,0.132114,0.113323,0.169221,0.195610,0.236700,...,0.440172,0,0.000000,0.062336,South West,False,South West,Marginal,50.263317,-5.051811
582,582,S14000067,"Argyll, Bute and South Lochaber",92300,0.144356,0.094268,0.095883,0.161023,0.241268,0.263202,...,0.378677,0,0.151740,0.023226,0,True,Scotland,Nat-Conservative,56.460349,-5.861842
621,621,S14000027,Na h-Eileanan an Iar,26600,0.152402,0.078341,0.093506,0.171434,0.238851,0.265465,...,0.079214,0,0.449046,0.082755,0,True,Scotland,Nat-Conservative,57.666667,-7.166667

In [8]:
get_lat_long("52 Portreath Dr, Derby DE22 2RZ")

52 Portreath Dr, Derby DE22 2RZ
Portreath Drive, Abbey Park, Allestree, Derby, England, DE22 2RR, United Kingdom
52.9497463 -1.4906424

(52.9497463, -1.4906424)

In [10]:
df_size = pd.read_csv("data/SAM_WPC_DEC_2020_UK.csv")

In [11]:
df_size

,WPC20CD,WPC20NM,AREAEHECT,AREACHECT,AREAIHECT,AREALHECT
0,E14000530,Aldershot,5297.82,5297.82,0.00,5297.82
1,E14000531,Aldridge-Brownhills,4401.65,4401.65,0.00,4401.65
2,E14000532,Altrincham and Sale West,5093.05,5093.05,0.00,5093.05
3,E14000533,Amber Valley,12464.64,12464.64,0.00,12464.64
4,E14000534,Arundel and South Downs,64651.28,64523.36,0.00,64523.36
...,...,...,...,...,...,...
645,W07000076,Caerphilly,11455.59,11455.59,0.00,11455.59
646,W07000077,Islwyn,11199.27,11199.27,0.00,11199.27
647,W07000078,Vale of Glamorgan,32187.61,31520.69,0.00,31520.69
648,W07000079,Cardiff West,5098.02,5098.02,0.00,5098.02
649,W07000080,Cardiff South and Penarth,5689.61,4790.82,150.19,4640.63

In [14]:
pd.merge(df, df_size, left_on="New constituency name", right_on="WPC20NM") #Losing 200 rows due to name/boundary changes

,Unnamed: 0,ONS code,New constituency name,Total population,Aged 15 years and under,Aged 16 to 24 years,Aged 25 to 34 years,Aged 35 to 49 years,Aged 50 to 64 years,Aged 65 years and over,...,Region,Cluster Des,Latitude,Longitude,WPC20CD,WPC20NM,AREAEHECT,AREACHECT,AREAIHECT,AREALHECT
0,1,E14001063,Aldershot,117430,0.185379,0.099821,0.158247,0.207732,0.187737,0.161083,...,South East,Brexit Conservative,51.249417,-0.763015,E14000530,Aldershot,5297.82,5297.82,0.00,5297.82
1,2,E14001064,Aldridge-Brownhills,93607,0.177914,0.089929,0.114617,0.177711,0.212078,0.227750,...,West Midlands,Conservative,52.598576,-1.926957,E14000531,Aldridge-Brownhills,4401.65,4401.65,0.00,4401.65
2,3,E14001065,Altrincham and Sale West,100924,0.212833,0.082260,0.100719,0.219046,0.194859,0.190282,...,North West,Brexit Conservative,53.398450,-2.351823,E14000532,Altrincham and Sale West,5093.05,5093.05,0.00,5093.05
3,4,W07000082,Alyn and Deeside,102072,0.181960,0.089956,0.130467,0.191326,0.208382,0.197909,...,Wales,Brexit,57.274096,-5.515916,W07000043,Alyn and Deeside,15685.74,15521.73,0.00,15521.73
4,5,E14001066,Amber Valley,90322,0.169521,0.086953,0.125004,0.179087,0.219529,0.219906,...,East Midlands,Conservative,53.029057,-1.462495,E14000533,Amber Valley,12464.64,12464.64,0.00,12464.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,624,S14000051,Orkney and Shetland,45500,0.168360,0.085686,0.113215,0.178166,0.224494,0.230079,...,Scotland,Anomalous,58.852057,-3.286940,S14000051,Orkney and Shetland,274377.56,248358.34,2558.37,245799.97
396,625,S14000101,Paisley and Renfrewshire North,90100,0.166508,0.097220,0.142050,0.189700,0.211715,0.192808,...,Scotland,SNP,55.833721,-4.441384,S14000052,Paisley and Renfrewshire North,13117.66,12342.47,0.00,12342.47
397,626,S14000102,Paisley and Renfrewshire South,88900,0.160005,0.101595,0.134629,0.179107,0.231333,0.193330,...,Scotland,SNP,55.845583,-4.423965,S14000053,Paisley and Renfrewshire South,13806.30,13806.30,0.00,13806.30
398,630,S14000058,West Aberdeenshire and Kincardine,97800,0.188758,0.085324,0.095580,0.206090,0.223372,0.200875,...,Scotland,Nat-Conservative,50.909538,-1.406866,S14000058,West Aberdeenshire and Kincardine,327186.85,326707.50,334.57,326372.93
399,631,S14000106,West Dunbartonshire,91300,0.173598,0.096575,0.127518,0.177969,0.228277,0.196063,...,Scotland,SNP,55.966667,-4.533333,S14000059,West Dunbartonshire,18278.30,17732.03,1855.47,15876.56